<?php

namespace LoginBundle\Repository;

/**
 * curso_docenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class curso_docenteRepository extends \Doctrine\ORM\EntityRepository
{
}
