<?php

namespace LoginBundle\Repository;

/**
 * docenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class docenteRepository extends \Doctrine\ORM\EntityRepository
{
}
