<?php

namespace LoginBundle\Repository;

/**
 * facultadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class facultadRepository extends \Doctrine\ORM\EntityRepository
{
}
