<?php

namespace LoginBundle\Repository;

/**
 * matriculaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class matriculaRepository extends \Doctrine\ORM\EntityRepository
{
}
