<?php

namespace LoginBundle\Repository;

/**
 * modalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
