<?php

namespace LoginBundle\Repository;

/**
 * periodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class periodoRepository extends \Doctrine\ORM\EntityRepository
{
}
