login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    #prefix:   /

principal:
    path:     /principal
    defaults: { _controller: LoginBundle:Default:dashboard }


#login:
#    resource: "@AccesoBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
