login:
    resource: "@LoginBundle/Controller/"
    type:     annotation
    #prefix:   /

#login:
#    resource: "@AccesoBundle/Resources/config/routing.yml"
#    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation
